[workspace]
authors = ["Hadrien Mary <hadrien.mary@gmail.com>"]
channels = ["conda-forge"]
name = "katago-onnx"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.11,<4"
jupyterlab = ">=4.5.1,<5"
pytorch = ">=2.9.1,<3"
httpx = ">=0.28.1,<0.29"
ruff = ">=0.14.10,<0.15"
ipywidgets = ">=8.1.8,<9"
tqdm = ">=4.67.1,<5"
ipykernel = ">=7.1.0,<8"
platformdirs = ">=4.5.1,<5"
onnxruntime = ">=1.22.2,<2"
onnxscript = ">=0.5.6,<0.6"
pandas = ">=2.3.3,<3"
typer = ">=0.21.0,<0.22"
huggingface_hub = ">=1.2.3,<2"

[pypi-dependencies]
katago-onnx = { path = ".", editable = true }
sgfmill = ">=1.1.1, <2"
